In [1]:
import pandas as pd
import numpy as np

In [2]:
w1 = input('enter first word:')
w2 = input('enter second word:')

enter first word:arash
enter second word:arsh


In [3]:
distArr=np.zeros((len(w1)+1,len(w2)+1))
decisionMadeArr=np.zeros((len(w1)+1,len(w2)+1))
delCost=1
insCost=1
potentialSubsCost=2
messageList=[] 
for i in range(0,len(w1)+1):
    distArr[i,0]=i
for i in range(0,len(w2)+1):
    distArr[0,i]=i
print(distArr)

[[0. 1. 2. 3. 4.]
 [1. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0.]
 [3. 0. 0. 0. 0.]
 [4. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0.]]


In [6]:
for i in range(1,len(w1)+1):
    for j in range(1,len(w2)+1):
        if w1[i-1] == w2[j-1]:
            subsCost=0
        else:
            subsCost=potentialSubsCost
        distArr[i,j]=min(distArr[i-1,j]+delCost,distArr[i,j-1]+insCost,distArr[i-1,j-1]+subsCost)
print(distArr)

[[0. 1. 2. 3. 4.]
 [1. 0. 1. 2. 3.]
 [2. 1. 0. 1. 2.]
 [3. 2. 1. 2. 3.]
 [4. 3. 2. 1. 2.]
 [5. 4. 3. 2. 1.]]


In [5]:
j=len(w2)
i=len(w1)
messageList=[];
decisionMadeArr[len(w1),len(w2)]=1
while i>0 or j>0:
    if w1[i-1] == w2[j-1]:
        subsCost=0
    else:
        subsCost=potentialSubsCost
    if(distArr[i,j]==distArr[i-1,j-1]+subsCost):
        decisionMadeArr[i-1,j-1]=1
        messageList.append('made a substitution between '+w1[i-1]+' and '+w2[j-1])
        i,j=i-1,j-1
    elif distArr[i,j]==distArr[i-1,j]+delCost:
        decisionMadeArr[i-1,j]=1
        messageList.append('deleted the '+w1[i-1])
        i=i-1
        
    elif distArr[i,j]==distArr[i,j-1]+delCost:
        decisionMadeArr[i,j-1]=1
        messageList.append('inserted the '+w2[j-1])
        j=j-1
print('converting ',w1,' to ',w2)
for i in reversed(range(0,len(messageList))):
    print(messageList[i])
print('\n','\n','the path:')
print(decisionMadeArr)

converting  arash  to  arsh
made a substitution between a and a
made a substitution between r and r
deleted the a
made a substitution between s and s
made a substitution between h and h

 
 the path:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
